---
title: "test_people"
output: html_document
---

```{r}
# Convert JSON to RDS

data <- fromJSON("Data/individual_data.json")
saveRDS(data, "Data/ind_data.rds")
```

```{r}
individuals <- readRDS("Data/ind_data.rds")
library(tidyverse)
name = "Kelly"
bio <- as.character(individuals[trimws(individuals$name) == name, "biography"][1])
```

```{r}
library(jsonlite)
# Example dataframe
df <- fromJSON("shinyapp/Data/individual_data.json")

# Function to convert the string to a numeric vector
convert_to_range <- function(string) {
  # Split the string by comma
  split_values <- unlist(strsplit(as.character(string), ","))
  
  # Convert to numeric
  numeric_vec <- as.numeric(split_values)
  
  # Ensure exactly two values (left and right of comma)
  if (length(numeric_vec) == 2) {
    return(numeric_vec)
  } else {
    warning("Invalid format: expected two numbers separated by a comma")
    return(c(NA, NA))  # Return NA if format is wrong
  }
}

saveRDS(df, "shinyapp/Data/ind_data.rds")
```

```{r}
library(jsonlite)
# Example dataframe
df <- fromJSON("shinyapp/Data/individual_weights.json")

saveRDS(df, "shinyapp/Data/ind_weights.rds")

```

